### ISSUE TITLE
利用的时候为什么需要刷新？

### ISSUE THREAD

**Issue by yq9721** [Y4er/yaml-payload#1]
最近把这个jar用在nacos的反序列化漏洞上了，通过刷新nacos配置，让微服务加载这个恶意的jar，从而注册一条路由。但是注册完如果不通过actuator的刷新接口则路由并未生效。看这篇文章https://my.oschina.net/u/4587690/blog/4649301介绍的应该是不用刷新的。麻烦帮忙解答下，谢谢。

**Comment by yq9721** [comment]
补充一下，我这里的场景是不需要刷新的，这个程序的场景确实需要刷新，因为env修改了必须刷新才生效，我遇到的问题是nacos刷新配置后就已经触发了一些列的代码执行了，为什么还是需要刷新后才能成功加载路由。

**Comment by yq9721** [comment]
问题进一步简化一下，就是在非web环境下如何获取到ApplicationContext的问题。

**Comment by Y4er** [comment]
没研究过，无法提供答复。

关于ApplicationContext可以参考

https://www.anquanke.com/post/id/198886

以及哥斯拉webshell工具的代码实现
